const APP_ACTIONS = {
  UI_ACTIONS: {
    SET_NOTIFICATION: 'SET_NOTIFICATION',
    SET_LOADING: 'SET_LOADING',
  },
  AUTH_ACTIONS: {
    SET_IS_AUTHENTICATED: 'SET_IS_AUTHENTICATED',
  },
  ADMIN_ACTIONS: {
    SET_DASHBOARD_STATS: 'SET_DASHBOARD_STATS',
  },
};

export default APP_ACTIONS;
